image: maven:3.3.9
pipelines:
  branches:
    master:
      - step:
          name: Prod Regression
          caches:
            - maven
          script:
            - mvn clean test
          artifacts:
            - allure-results/**
            - reports/**
