image: maven:3.6.3
pipelines:
  branches:
    master:
      - step:
          name: Prod Regression
          caches:
            - maven
          script:
            - mvn clean test -Pqa -Denv=qa
            #- mvn allure:report
          artifacts:
            - allure-results/**
            - reports/**
