image: maven:3.3.9
pipelines:
  branches:
    master:
    - step:
        name: Build and Test
        caches:
          - maven
        script:
          - mvn clean test
          - mvn allure:report
        artifacts:
          - allure-results/**
          - reports/**
