image: maven:3.6.3
pipelines:
  branches:
    master:
      - step:
          name: Prod Regression
          caches:
            - maven
          script:
            - mvn clean test
            - mvn allure:report
            - cp -r xxx/target/* $BITBUCKET_CLONE_DIR/dist
          artifacts:
            - allure-results/**
            - '**/target/**'
